#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-unbound.json" ] && {
    cat > /usr/share/ucitrack/luci-app-unbound.json << EEOF
{
    "config": "unbound",
    "init": "unbound"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
  delete ucitrack.@unbound[-1]
  add ucitrack unbound
  set ucitrack.@unbound[-1].init=unbound
  commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0

