#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-bridge.json" ] && {
    cat > /usr/share/ucitrack/luci-app-bridge.json << EEOF
{
    "config": "bridge",
    "init": "bridge"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@bridge[-1]
	add ucitrack bridge
	set ucitrack.@bridge[-1].init=bridge
	commit ucitrack
EOF

chmod +x /etc/init.d/bridge

rm -f /tmp/luci-indexcache
exit 0
