#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-pagekitec.json" ] && {
    cat > /usr/share/ucitrack/luci-app-pagekitec.json << EEOF
{
    "config": "pagekitec",
    "init": "pagekitec"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@pagekitec[-1]
	add ucitrack pagekitec
	set ucitrack.@pagekitec[-1].init=pagekitec
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
