#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-pppoe-relay.json" ] && {
    cat > /usr/share/ucitrack/luci-app-pppoe-relay.json << EEOF
{
    "config": "pppoe-relay",
    "init": "pppoe-relay"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@pppoe-relay[-1]
	add ucitrack pppoe-relay
	set ucitrack.@pppoe-relay[-1].init=pppoe-relay
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
