#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-irqbalance.json" ] && {
    cat > /usr/share/ucitrack/luci-app-irqbalance.json << EEOF
{
    "config": "irqbalance",
    "init": "irqbalance"
}
EEOF
}

[ -f "/etc/config/ucitrack" ] && {
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@irqbalance[-1]
	add ucitrack irqbalance
	set ucitrack.@irqbalance[-1].init=irqbalance
	commit ucitrack
EOF
}

exit 0

