#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-shairport-sync.json" ] && {
    cat > /usr/share/ucitrack/luci-app-shairport-sync.json << EEOF
{
    "config": "shairport-sync",
    "init": "shairport-sync"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@shairport-sync[-1]
	add ucitrack shairport-sync
	set ucitrack.@shairport-sync[-1].init=shairport-sync
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
