#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-udpxy.json" ] && {
    cat > /usr/share/ucitrack/luci-app-udpxy.json << EEOF
{
    "config": "udpxy",
    "init": "udpxy"
}
EEOF
}

# needed for "Save and Apply" to restart udpxy
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@udpxy[-1]
	add ucitrack udpxy
	set ucitrack.@udpxy[-1].init="udpxy"
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
