#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-mentohust.json" ] && {
    cat > /usr/share/ucitrack/luci-app-mentohust.json << EEOF
{
    "config": "mentohust",
    "init": "mentohust"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@mentohust[-1]
	add ucitrack mentohust
	set ucitrack.@mentohust[-1].init=mentohust
	commit ucitrack
EOF

rm -rf /tmp/luci-*
exit 0
