#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-cd8021x.json" ] && {
    cat > /usr/share/ucitrack/luci-app-cd8021x.json << EEOF
{
    "config": "cd8021x",
    "init": "cd8021x"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@cd8021x[-1]
	add ucitrack cd8021x
	set ucitrack.@cd8021x[-1].init=cd8021x
EOF

rm -rf /tmp/luci-indexcache*
exit 0
