#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-dump1090.json" ] && {
    cat > /usr/share/ucitrack/luci-app-dump1090.json << EEOF
{
    "config": "dump1090",
    "init": "dump1090"
}
EEOF
}

# needed for "Save and Apply" to restart dump1090
uci -q batch <<-EOF >/dev/null
	delete ucitrack.@dump1090[-1]
	add ucitrack dump1090
	set ucitrack.@dump1090[-1].init="dump1090"
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
