#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-dockerd.json" ] && {
    cat > /usr/share/ucitrack/luci-app-dockerd.json << EEOF
{
    "config": "dockerd",
    "init": "dockerd"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@dockerd[-1]
	add ucitrack dockerd
	set ucitrack.@dockerd[-1].init=dockerd
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
