#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-owntone.json" ] && {
    cat > /usr/share/ucitrack/luci-app-owntone.json << EEOF
{
    "config": "owntone",
    "init": "owntone"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@owntone[-1]
	add ucitrack owntone
	set ucitrack.@owntone[-1].init=owntone
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
