#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-ngrokc.json" ] && {
    cat > /usr/share/ucitrack/luci-app-ngrokc.json << EEOF
{
    "config": "ngrokc",
    "init": "ngrokc"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@ngrokc[-1]
	add ucitrack ngrokc
	set ucitrack.@ngrokc[-1].init=ngrokc
	commit ucitrack
EOF

rm -f /tmp/luci-indexcache
exit 0
