#!/bin/sh
[ ! -f "/usr/share/ucitrack/luci-app-upnpd.json" ] && {
    cat > /usr/share/ucitrack/luci-app-upnpd.json << EEOF
{
    "config": "upnpd",
    "init": "upnpd"
}
EEOF
}

uci -q batch <<-EOF >/dev/null
	delete ucitrack.@upnpd[-1]
	add ucitrack upnpd
	set ucitrack.@upnpd[-1].init=miniupnpd
	commit ucitrack
EOF

exit 0
